runtime: nodejs20
service: messenger

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

handlers:
  - url: /.*
    script: auto