name: Deployment

on:
  push:
    branches:
    - main
  
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.5.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          version: main
          credentials: ${{secrets.GCP_CREDENTIALS}}
          flags: --no-cache
